const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.GD_SDK,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.GD_SDK.Cnds.ResumeGame
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{Tween: 0},
	{btnMusic: 0},
	{btnPlay: 0},
	{index: 0},
	{TextLogo: 0},
	{btnFullscreen: 0},
	{Sine: 0},
	{Logo: 0},
	{TiledBackground: 0},
	{btnLanguage: 0},
	{btnInfo: 0},
	{LogoInfo: 0},
	{backgroundNameCounty: 0},
	{Index: 0},
	{button: 0},
	{flag: 0},
	{btnMenu: 0},
	{btnHome: 0},
	{HeartIndex: 0},
	{heart: 0},
	{backgroundOver: 0},
	{TXT_Count: 0},
	{TXT_Win: 0},
	{background: 0},
	{backgroundFlag: 0},
	{boardReward: 0},
	{btnAd: 0},
	{btnClose: 0},
	{Browser: 0},
	{Touch: 0},
	{AJAX: 0},
	{Array: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{Chans: 0},
	{GameDistributionSDK: 0},
	{LocalStorage: 0},
	{Language: 0},
	{buttonTrue: 0},
	{Heart: 0},
	{Count: 0},
	{FrameCopy: 0},
	{Frame: 0},
	{SelfIndex: 0},
	{Sound: 0}
];

self.InstanceType = {
	btnMusic: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	TextLogo: class extends self.ITextInstance {},
	btnFullscreen: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	btnLanguage: class extends self.ISpriteInstance {},
	btnInfo: class extends self.ISpriteInstance {},
	LogoInfo: class extends self.ISpriteInstance {},
	backgroundNameCounty: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	backgroundOver: class extends self.ISpriteInstance {},
	TXT_Count: class extends self.ITextInstance {},
	TXT_Win: class extends self.ITextInstance {},
	background: class extends self.ISpriteInstance {},
	backgroundFlag: class extends self.ISpriteInstance {},
	boardReward: class extends self.ISpriteInstance {},
	btnAd: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Chans: class extends self.IArrayInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {}
}